# Generated by Django 4.2.30 on 2026-07-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.IntegerField(blank=True, null=True)),
                ('disease', models.CharField(max_length=150)),
                ('barangay_name', models.CharField(max_length=100)),
                ('severity_level', models.CharField(max_length=50)),
                ('final_risk_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('anomaly_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('environmental_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('spatial_metric', models.TextField(blank=True, null=True)),
                ('temporal_metric', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_notifications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppNotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=50)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='dashboard.appnotification')),
            ],
            options={
                'db_table': 'app_notification_reads',
                'managed': True,
                'unique_together': {('notification', 'user_id', 'user_type')},
            },
        ),
    ]
