# Generated by Django 4.2.30 on 2026-09-29 14:48

from django.db import migrations, models


def approve_existing_notifications(apps, schema_editor):
    AppNotification = apps.get_model('dashboard', 'AppNotification')
    for notification in AppNotification.objects.all().iterator():
        trigger = (notification.trigger_source or '').strip().casefold()
        if 'threshold' in trigger:
            trigger_code = 'pidsr_threshold'
        elif 'cluster' in trigger:
            trigger_code = 'spatial_cluster'
        else:
            trigger_code = 'aptas_anomaly'
        AppNotification.objects.filter(pk=notification.pk).update(
            review_status='approved',
            trigger_code=trigger_code,
            trigger_source=(
                'High Anomaly Score'
                if trigger == 'new confirmed case'
                else notification.trigger_source
            ),
            sent_at=notification.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_appnotification_active_cases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='recommendation_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending Admin Review'), ('approved', 'Approved and Sent'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='reviewed_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='reviewed_by_role',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='source_report_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='trigger_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(
            approve_existing_notifications,
            migrations.RunPython.noop,
        ),
    ]
