# Generated by Django 6.0.6 on 2026-06-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayRiskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=100)),
                ('syndrome', models.CharField(max_length=100)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('temporal_score', models.FloatField(default=0.0)),
                ('environmental_score', models.FloatField(default=0.0)),
                ('spatial_score', models.FloatField(default=0.0)),
                ('final_risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=20)),
                ('is_active_alert', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'barangay_risk_logs',
                'ordering': ['-final_risk_score', '-created_at'],
                'indexes': [models.Index(fields=['barangay', 'syndrome'], name='barangay_ri_baranga_cb1564_idx'), models.Index(fields=['is_active_alert', '-created_at'], name='barangay_ri_is_acti_5c3905_idx')],
            },
        ),
    ]
