# Generated by Django 4.2.30 on 2026-07-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_barangay_risk_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangayrisklog',
            options={'managed': False, 'ordering': ['-final_risk_score', '-created_at']},
        ),
    ]
