# Generated by Django 4.2.30 on 2026-07-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_patient_demographics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bhw',
            fields=[
                ('id', models.AutoField(db_column='bhw_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_info', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bhw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnvironmentData',
            fields=[
                ('id', models.AutoField(db_column='environment_id', primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weather_condition', models.CharField(max_length=100)),
                ('recorded_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'environment_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.AutoField(db_column='report_id', primary_key=True, serialize=False)),
                ('symptoms', models.TextField()),
                ('severity_level', models.CharField(max_length=50)),
                ('report_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'health_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalRecord',
            fields=[
                ('id', models.AutoField(db_column='record_id', primary_key=True, serialize=False)),
                ('disease_type', models.CharField(max_length=100)),
                ('case_status', models.CharField(max_length=50)),
                ('treatment_status', models.CharField(max_length=100)),
                ('date_recorded', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historical_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.AutoField(db_column='incident_id', primary_key=True, serialize=False)),
                ('disease_type', models.CharField(max_length=100)),
                ('case_count', models.IntegerField()),
                ('incident_date', models.DateField()),
                ('response_action', models.TextField()),
            ],
            options={
                'db_table': 'incident_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyAdmin',
            fields=[
                ('id', models.AutoField(db_column='admin_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyNotification',
            fields=[
                ('id', models.AutoField(db_column='notification_id', primary_key=True, serialize=False)),
                ('recipient_role', models.CharField(max_length=100)),
                ('notification_message', models.TextField()),
                ('sent_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacySuperAdmin',
            fields=[
                ('id', models.AutoField(db_column='super_admin_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'super_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MlAiPrediction',
            fields=[
                ('id', models.AutoField(db_column='prediction_id', primary_key=True, serialize=False)),
                ('disease_type', models.CharField(max_length=100)),
                ('risk_score', models.FloatField()),
                ('prediction_probability', models.FloatField()),
                ('severity_level', models.CharField(max_length=50)),
                ('algorithm_used', models.CharField(max_length=100)),
                ('prediction_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'ml_ai_predictions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(db_column='patient_id', primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('birthdate', models.DateField()),
            ],
            options={
                'db_table': 'patients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAnalysis',
            fields=[
                ('id', models.AutoField(db_column='analysis_id', primary_key=True, serialize=False)),
                ('risk_score', models.FloatField()),
                ('anomaly_flag', models.BooleanField()),
                ('analysis_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'risk_analysis',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='barangay',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='barangayepidemicstatus',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='diseasecategorythreshold',
            options={'managed': False, 'ordering': ['category_level']},
        ),
        migrations.AlterModelOptions(
            name='environmentaldata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mitigationprotocol',
            options={'managed': False, 'ordering': ['disease_label', '-priority', 'sort_order']},
        ),
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ocrresult',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='outbreakthresholdlog',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='patientcase',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pulsesession',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='registrationrequest',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='riskassessment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='superadmin',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='surveillancereport',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='surveillancesession',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='systemlog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
