# Generated by Django 4.2.30 on 2026-08-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_pidsr_symptom_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutbreakThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_label', models.CharField(max_length=150, unique=True)),
                ('case_threshold', models.PositiveSmallIntegerField(default=3)),
                ('rolling_window_days', models.PositiveSmallIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'outbreak_thresholds',
                'ordering': ['disease_label'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FieldTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatched_tasks', to='myapp.user')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='myapp.user')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='myapp.surveillancereport')),
            ],
            options={
                'db_table': 'myapp_fieldtask',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
