# Generated by Django 4.2.30 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_expand_pidsr_category_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRevision',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('payload', models.JSONField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending Approval'),
                            ('approved', 'Approved'),
                            ('rejected', 'Rejected'),
                            ('superseded', 'Superseded'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                (
                    'change_summary',
                    models.CharField(blank=True, default='', max_length=255),
                ),
                ('created_by_id', models.PositiveIntegerField()),
                ('created_by_role', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'approved_by_id',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    'approved_by_role',
                    models.CharField(blank=True, default='', max_length=20),
                ),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recommendation_revisions',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
