# Generated by Django 4.2.30 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_recommendationrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationrevision',
            name='scope_disease',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
